/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const CheckFunctionArgs = t.iface([], {
  "projectPath": "string",
});

export const CheckFunction = t.func("boolean", t.param("args", "CheckFunctionArgs"));

export const Check = t.iface([], {
  "name": "string",
  "description": t.opt("string"),
  "onlyForReposWithLabels": t.opt(t.array("string")),
  "skip": t.opt("boolean"),
  "checkFunction": "CheckFunction",
});

const exportedTypeSuite: t.ITypeSuite = {
  CheckFunctionArgs,
  CheckFunction,
  Check,
};
export default exportedTypeSuite;
