/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Check = t.iface([], {
  "name": "string",
  "description": "string",
  "skip": t.opt("boolean"),
  "checkFunction": t.func("boolean", t.param("projectName", "string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  Check,
};
export default exportedTypeSuite;
